import React, { useState } from 'react';
import { Check, X } from 'lucide-react';
import { API_BASE } from '../../config.js';
import type { SuggestedJob } from './types.js';

interface Props {
  jobs: SuggestedJob[];
  loading: boolean;
  onJobStatusChange: (id: string, status: 'applied' | 'dismissed') => void;
}

const priorityColor = (p: string) => {
  if (p === 'critical') return 'text-red-500 bg-red-500/10 border-red-500/30';
  if (p === 'high') return 'text-red-400 bg-red-400/10 border-red-400/20';
  if (p === 'medium') return 'text-yellow-400 bg-yellow-400/10 border-yellow-400/20';
  return 'text-ide-text-dim bg-ide-panel border-ide-border';
};

const categoryColor = (cat: string) => {
  if (cat === 'model_tool_enhancement') return 'text-purple-400 bg-purple-500/10';
  if (cat === 'model_config_promotion') return 'text-green-400 bg-green-500/10';
  return 'text-blue-400 bg-blue-500/10';
};

const statusBadge = (s: string) => {
  if (s === 'applied') return 'text-green-400 bg-green-500/10 border-green-500/20';
  if (s === 'dismissed') return 'text-ide-text-dim bg-ide-panel border-ide-border';
  return 'text-yellow-400 bg-yellow-500/10 border-yellow-500/20';
};

export function JobsTab({ jobs, loading, onJobStatusChange }: Props) {
  const [updating, setUpdating] = useState<string | null>(null);
  const [expandedId, setExpandedId] = useState<string | null>(null);

  const handleStatus = async (id: string, status: 'applied' | 'dismissed') => {
    setUpdating(id);
    try {
      const res = await fetch(`${API_BASE}/api/blame/jobs/${id}/status`, {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({ status }),
      });
      if (res.ok) {
        onJobStatusChange(id, status);
      }
    } catch {
      // best effort
    }
    setUpdating(null);
  };

  if (loading) {
    return <div className="p-3 text-ide-text-dim text-[10px]">Loading suggested jobs…</div>;
  }

  if (jobs.length === 0) {
    return (
      <div className="p-3 text-center text-ide-text-dim text-[10px]">
        No suggested jobs. Jobs are generated by tool criticism records and success attributions.
      </div>
    );
  }

  const pending = jobs.filter(j => j.status === 'pending');
  const resolved = jobs.filter(j => j.status !== 'pending');

  return (
    <div className="p-3 space-y-2">
      {pending.length > 0 && (
        <>
          <div className="text-[9px] text-ide-text-dim uppercase tracking-wider px-0.5">
            Pending ({pending.length})
          </div>
          {pending.map(job => renderJob(job))}
        </>
      )}

      {resolved.length > 0 && (
        <>
          <div className="text-[9px] text-ide-text-dim uppercase tracking-wider px-0.5 mt-2">
            Resolved ({resolved.length})
          </div>
          {resolved.map(job => renderJob(job))}
        </>
      )}
    </div>
  );

  function renderJob(job: SuggestedJob) {
    const isExpanded = expandedId === job.id;
    return (
      <div key={job.id} className={`border rounded ${job.status === 'dismissed' ? 'opacity-50' : ''}`} style={{ borderColor: 'var(--ide-border)' }}>
        <div className="flex items-start gap-2 px-2 py-1.5">
          <button
            className="flex-1 min-w-0 text-left"
            onClick={() => setExpandedId(prev => prev === job.id ? null : job.id)}
          >
            <div className="flex items-center gap-1.5 mb-0.5 flex-wrap">
              <span className={`text-[9px] px-1 py-0.5 rounded border ${categoryColor(job.category)}`}>
                {job.category.replace(/_/g, ' ')}
              </span>
              <span className={`text-[9px] px-1 py-0.5 rounded border ${priorityColor(job.priority)}`}>
                {job.priority}
              </span>
              <span className={`text-[9px] px-1 py-0.5 rounded border ${statusBadge(job.status)}`}>
                {job.status}
              </span>
            </div>
            <div className="text-ide-text text-[10px] font-medium truncate">{job.title}</div>
            <div className="text-ide-text-dim text-[9px] truncate">{job.description}</div>
          </button>

          {job.status === 'pending' && (
            <div className="flex gap-1 flex-shrink-0 mt-0.5">
              <button
                onClick={() => handleStatus(job.id, 'applied')}
                disabled={updating === job.id}
                title="Apply"
                className="p-1 rounded bg-green-500/15 text-green-400 hover:bg-green-500/30 disabled:opacity-50"
              >
                <Check className="w-3 h-3" />
              </button>
              <button
                onClick={() => handleStatus(job.id, 'dismissed')}
                disabled={updating === job.id}
                title="Dismiss"
                className="p-1 rounded bg-ide-panel text-ide-text-dim hover:text-red-400 border border-ide-border disabled:opacity-50"
              >
                <X className="w-3 h-3" />
              </button>
            </div>
          )}
        </div>

        {isExpanded && (
          <div className="px-3 pb-2 pt-1 border-t border-ide-border/40 space-y-1.5 text-[9px]">
            <div className="text-ide-text-dim uppercase tracking-wider">Payload</div>
            <pre className="text-ide-text-dim bg-ide-panel/40 rounded px-2 py-1.5 overflow-x-auto text-[8px] leading-relaxed border border-ide-border/30 whitespace-pre-wrap">
              {JSON.stringify(job.payload, null, 2)}
            </pre>
            <div className="flex gap-4 text-ide-text-dim/60">
              <span>Created: {new Date(job.createdAt).toLocaleString()}</span>
              <span>Source: {job.source}</span>
            </div>
          </div>
        )}
      </div>
    );
  }
}
