#!/usr/bin/env python3
"""
Launch Script for Rebuilt Project
Auto-generated by Ultimate Auto-Rebuilder
"""

import sys
import os
from pathlib import Path

# Add the current directory to Python path
sys.path.insert(0, str(Path(__file__).parent))

def main():
    """Main entry point for the rebuilt project"""
    print("🚀 Launching rebuilt project...")
    
    # Import all packages to test
    try:
        import core
        print("✅ Core package loaded")
    except ImportError as e:
        print(f"⚠️  Core package error: {e}")
    
    try:
        import ui
        print("✅ UI package loaded")
    except ImportError as e:
        print(f"⚠️  UI package error: {e}")
    
    try:
        import io
        print("✅ IO package loaded")  
    except ImportError as e:
        print(f"⚠️  IO package error: {e}")
    
    try:
        import net
        print("✅ Net package loaded")
    except ImportError as e:
        print(f"⚠️  Net package error: {e}")
    
    try:
        import train
        print("✅ Train package loaded")
    except ImportError as e:
        print(f"⚠️  Train package error: {e}")
    
    try:
        import tools
        print("✅ Tools package loaded")
    except ImportError as e:
        print(f"⚠️  Tools package error: {e}")
    
    print("🎉 Project launch complete!")

if __name__ == "__main__":
    main()
